package main;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;
import org.junit.runners.Suite.SuiteClasses;

import tests.*;

@RunWith(Suite.class)
@SuiteClasses({
	LoginAsAdminTest.class,
	BadLoginTest.class,
	EmptyLoginTest.class,
	AddUserTest.class,
	LoginAsNewUserTest.class,
	BadSiteAdminLoginTest.class,
	EmptySiteAdminLoginTest.class,
	AddEmptyUserFailsTest.class,	
	AddExistingUserFailsTest.class, 
	AddNewArticleTest.class,
	CheckNewArticleTest.class,
	AddEmptyArticleTest.class,
	EditArticleTest.class,
	CheckEditedArticleTest.class,
	AddTagTest.class,
	AddEmptyTagTest.class,
	AddExistingTagFailsTest.class,
	AssignTagToArticleTest.class,
	CheckArticleTagTest.class,
	AddCategoryTest.class,
	AddEmptyCategoryTest.class,
	AddExistingCategoryFailsTest.class,
	AssignCategoryTest.class,
	CheckAssignedCategoryTest.class,
	ChangePasswordTest.class,
	ChangePasswordDontMatchTest.class,
	ChangePasswordTooShortTest.class,
	AddMenuItemTest.class,
	AddMenuItemEmptyTitleTest.class,
	AddMenuItemMenuNotSelectedTest.class,
	AddMenuItemEmptyMenuTypeTest.class,
	AddExistingMenuItemFailsTest.class,
	ArchiveArticleTest.class,
	SeeArchivedArticleTest.class,
	AddMenuTest.class,
	AddEmptyMenuTest.class,
	AddExistingMenuFailsTest.class,
	AddMenuDescriptionTest.class,
	AddBannerSiteModuleTest.class,
	AddBannerTest.class,
	AddClientTest.class,
	AddEmptyClientFailsTest.class,
	AddBannerUrlTest.class,
	AddBannerClientTest.class,
	TrackBannerImpressionsTest.class,
	CheckTrackingBannerImpressionsWorksTest.class,
	AddContactTest.class,
	AddEmptyContactTest.class,
	AddExistingContactFailsTest.class,
	LinkUserToContactTest.class,
	CheckUserLinkedToContactTest.class,
	AddContactInfoTest.class,
	AddNewsFeedTest.class,
	AddEmptyNewsFeedTest.class,
	AddExistingNewsFeedFailsTest.class,
	AddGroupTest.class,
	AddEmptyGroupTest.class,
	AddExistingGroupFailsTest.class,
	AssignUserToGroupTest.class,
	CheckUserAssignedToGroupTest.class,
	AddFieldTest.class,
	AddEmptyFieldTest.class,
	AddExistingFieldFailsTest.class,
	AddFieldGroupTest.class,
	AddEmptyFieldGroupTest.class,
	AssignFieldToGroupTest.class,
	AddAccessLevelTest.class,
	AddEmptyAccessLevelFailsTest.class,
	AddExistingAccessLevelFailsTest.class,
	AssignAccessLevelToUserGroupTest.class,
	DeleteAccessLevelTest.class,
	DeleteMenuItemTest.class,
	DeleteMenuTest.class,
	DeleteBannerTest.class,
	DeleteBannerSiteModuleTest.class,
	DeleteClientTest.class,
	DeleteContactTest.class,
	DeleteNewsFeedTest.class,
	DeleteTagTest.class,
	DeleteArticleTest.class,
	DeleteUserGroupTest.class,
	DeleteFieldGroupTest.class,
	DeleteFieldTest.class,
	DeleteUserTest.class,
	DeleteCategoryTest.class,

		
})

public class TestSuite {
}
